name: base
Channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-caret
  - r-ellipse
